/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bgl.coding.exercise;

public class GameOfLife {
  public int run() {
    // TODO: feel free to change this (including the function signature and implementation) and add your solution
    return 1;
  }
}
